// A thin simulator over the compiled Practice Proof contract.
//
// Identity here is the witness secret, not an injected caller address. That
// mirrors how the real contract works: you cannot impersonate another user by
// claiming their identity, because the identity is derived from a secret inside
// the ZK circuit. Switching actor means switching secret.

import {
  createConstructorContext,
  createCircuitContext,
  dummyContractAddress,
} from "@midnight-ntwrk/compact-runtime";

// Generated by `npm run build` (gitignored). Build before typechecking.
import { Contract, ledger } from "../build/practice_attestation/contract/index.js";

import {
  witnesses,
  padCommitments,
  MAX_SESSIONS,
  COMMITMENT_BYTES,
  type PracticePrivateState,
} from "../src/witnesses.js";

const ADDR = dummyContractAddress();
const COIN_PK = "0".repeat(64);

/** A deterministic 32-byte value built from a single fill byte. */
export const bytes32 = (fill: number): Uint8Array =>
  new Uint8Array(COMMITMENT_BYTES).fill(fill);

/** N distinct commitments, padded to the circuit width. */
export const commitmentSet = (n: number): Uint8Array[] =>
  padCommitments(Array.from({ length: n }, (_, i) => bytes32(i + 1)));

export const toHex = (u8: Uint8Array): string => Buffer.from(u8).toString("hex");

export type LedgerView = {
  milestones: {
    isEmpty(): boolean;
    size(): bigint;
    member(key: Uint8Array): boolean;
    lookup(key: Uint8Array): bigint;
    [Symbol.iterator](): Iterator<[Uint8Array, bigint]>;
  };
};

export class PracticeSim {
  private state: any;
  private active: PracticePrivateState;
  readonly contract: any;

  constructor(deployer: PracticePrivateState) {
    this.contract = new Contract(witnesses);
    this.active = deployer;
    const deploy = this.contract.initialState(
      createConstructorContext(deployer, COIN_PK),
    );
    // initialState returns a ContractState, whose `.data` is the ChargedState;
    // a circuit call returns a ChargedState directly. Normalise to ChargedState
    // so `ledger()` and `createCircuitContext()` see one consistent type.
    this.state = deploy.currentContractState.data;
  }

  /** Select the private state (i.e. the actor) used for the NEXT call. */
  as(ps: PracticePrivateState): this {
    this.active = ps;
    return this;
  }

  /** Call attest; commits the evolved ledger state on success. */
  attest(claimed: number): void {
    const ctx = createCircuitContext(ADDR, COIN_PK, this.state, this.active);
    const res = this.contract.circuits.attest(ctx, BigInt(claimed));
    this.state = res.context.currentQueryContext.state;
  }

  ledger(): LedgerView {
    return ledger(this.state) as LedgerView;
  }

  /** Every (identity, milestone) pair currently on the public ledger. */
  entries(): Array<[string, bigint]> {
    return [...this.ledger().milestones].map(([k, v]) => [toHex(k), v]);
  }
}

/** Build a private state: a secret plus `n` distinct real commitments. */
export const actor = (secretFill: number, n: number): PracticePrivateState => ({
  secretKey: bytes32(secretFill),
  commitments: commitmentSet(n),
});

export { MAX_SESSIONS, COMMITMENT_BYTES, padCommitments };
